INFO C:\Users\User\PycharmProjects\specialization\django\seminars\testapp\views.py changed, reloading.
INFO C:\Users\User\PycharmProjects\specialization\django\seminars\testapp\models.py changed, reloading.
INFO "GET / HTTP/1.1" 200 22
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 18
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 18
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 18
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 18
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 18
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 18
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 18
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 18
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 18
INFO C:\Users\User\PycharmProjects\specialization\django\seminars\testapp\models.py changed, reloading.
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 18
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 18
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 18
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 18
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 18
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 18
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 18
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 18
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 18
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 18
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 18
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 18
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 18
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 18
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 18
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 18
INFO C:\Users\User\PycharmProjects\specialization\django\seminars\testapp\views.py changed, reloading.
INFO C:\Users\User\PycharmProjects\specialization\django\seminars\testapp\views.py changed, reloading.
INFO "GET / HTTP/1.1" 200 22
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 8
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 8
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 8
INFO C:\Users\User\PycharmProjects\specialization\django\seminars\testapp\views.py changed, reloading.
INFO Used eagle_or_tails
ERROR Internal Server Error: /test/game1/
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\django\seminars\testapp\views.py", line 24, in eagle_or_tails
    return HttpResponse(**self)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\http\response.py", line 374, in __init__
    super().__init__(*args, **kwargs)
TypeError: HttpResponseBase.__init__() got an unexpected keyword argument '���'
ERROR "GET /test/game1/ HTTP/1.1" 500 72539
INFO C:\Users\User\PycharmProjects\specialization\django\seminars\testapp\views.py changed, reloading.
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 18
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 18
INFO C:\Users\User\PycharmProjects\specialization\django\seminars\testapp\views.py changed, reloading.
INFO C:\Users\User\PycharmProjects\specialization\django\seminars\testapp\views.py changed, reloading.
INFO "GET / HTTP/1.1" 200 22
WARNING Not Found: /favicon.ico
WARNING "GET /favicon.ico HTTP/1.1" 404 2483
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 32
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 32
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 32
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 32
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 32
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 32
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 32
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 32
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 32
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 32
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 32
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 32
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 32
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 32
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 32
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 32
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 32
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 32
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 32
INFO C:\Users\User\PycharmProjects\specialization\django\seminars\testapp\views.py changed, reloading.
INFO C:\Users\User\PycharmProjects\specialization\django\seminars\testapp\views.py changed, reloading.
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 82
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 82
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 82
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 82
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 82
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 82
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 82
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 82
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 82
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 82
INFO C:\Users\User\PycharmProjects\specialization\django\seminars\testapp\views.py changed, reloading.
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 48
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 48
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 48
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 48
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 48
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 48
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 48
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 48
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 48
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 48
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 48
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 48
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 48
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 48
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 48
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 48
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 48
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 48
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 48
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 48
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 48
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 48
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 48
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 48
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 48
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 48
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 48
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 48
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 48
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 48
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 48
INFO C:\Users\User\PycharmProjects\specialization\django\seminars\testapp\views.py changed, reloading.
INFO "GET / HTTP/1.1" 200 22
WARNING Not Found: /favicon.ico
WARNING "GET /favicon.ico HTTP/1.1" 404 2483
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 94
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 94
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 94
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 94
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 94
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 94
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 94
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 94
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 94
INFO "GET / HTTP/1.1" 200 22
WARNING Not Found: /favicon.ico
WARNING "GET /favicon.ico HTTP/1.1" 404 2487
WARNING Not Found: /game1
WARNING "GET /game1 HTTP/1.1" 404 2469
INFO Used index
INFO "GET /test/ HTTP/1.1" 200 13
INFO "GET /test/game1 HTTP/1.1" 301 0
INFO Used eagle_or_tails
ERROR Internal Server Error: /test/game1/
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: testapp_eagletails

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\django\seminars\project1\testapp\views.py", line 25, in eagle_or_tails
    res_w.save()
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\models\base.py", line 1020, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\models\base.py", line 1061, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\models\query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: testapp_eagletails
ERROR "GET /test/game1/ HTTP/1.1" 500 147505
INFO "GET /games/game2 HTTP/1.1" 301 0
INFO Game 2 is used
INFO "GET /games/game2/ HTTP/1.1" 200 43
INFO "GET /games/game1 HTTP/1.1" 301 0
INFO Game 1 is used
INFO "GET /games/game1/ HTTP/1.1" 200 23
WARNING Not Found: /games/statistic/
WARNING "GET /games/statistic/ HTTP/1.1" 404 2942
ERROR Internal Server Error: /admin/
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 187, in _get_session
    return self._session_cache
           ^^^^^^^^^^^^^^^^^^^
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: django_session

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\contrib\admin\sites.py", line 261, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\contrib\admin\sites.py", line 230, in inner
    if not self.has_permission(request):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\contrib\admin\sites.py", line 203, in has_permission
    return request.user.is_active and request.user.is_staff
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\utils\functional.py", line 266, in inner
    self._setup()
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\utils\functional.py", line 419, in _setup
    self._wrapped = self._setupfunc()
                    ^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\contrib\auth\middleware.py", line 25, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
                                            ^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\contrib\auth\middleware.py", line 11, in get_user
    request._cached_user = auth.get_user(request)
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 191, in get_user
    user_id = _get_user_session_key(request)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 60, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
                                               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 53, in __getitem__
    return self._session[key]
           ^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 192, in _get_session
    self._session_cache = self.load()
                          ^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\contrib\sessions\backends\db.py", line 42, in load
    s = self._get_session_from_db()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\contrib\sessions\backends\db.py", line 32, in _get_session_from_db
    return self.model.objects.get(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\models\query.py", line 633, in get
    num = len(clone)
          ^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: django_session
ERROR "GET /admin/ HTTP/1.1" 500 201082
INFO Used eagle_or_tails
ERROR Internal Server Error: /test/game1/
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: testapp_eagletails

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\django\seminars\project1\testapp\views.py", line 25, in eagle_or_tails
    res_w.save()
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\models\base.py", line 1020, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\models\base.py", line 1061, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\models\query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: testapp_eagletails
ERROR "GET /test/game1/ HTTP/1.1" 500 147505
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 94
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 94
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 94
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 94
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 94
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 94
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 94
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 94
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 94
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 94
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 94
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 94
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 94
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 94
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 94
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 94
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 94
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 94
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 94
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 94
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 94
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 94
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 94
INFO Used eagle_or_tails
INFO "GET /test/game1/ HTTP/1.1" 200 94
INFO "GET / HTTP/1.1" 200 22
WARNING Not Found: /favicon.ico
WARNING "GET /favicon.ico HTTP/1.1" 404 2487
INFO "GET /admin/ HTTP/1.1" 302 0
INFO "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4267
INFO "POST /admin/login/?next=/admin/ HTTP/1.1" 200 4534
INFO "POST /admin/login/?next=/admin/ HTTP/1.1" 200 4534
INFO "GET / HTTP/1.1" 200 22
WARNING Not Found: /favicon.ico
WARNING "GET /favicon.ico HTTP/1.1" 404 2487
WARNING Not Found: /about
WARNING "GET /about HTTP/1.1" 404 2469
INFO "GET /admin/ HTTP/1.1" 302 0
INFO "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4267
INFO "POST /admin/login/?next=/admin/ HTTP/1.1" 200 4534
INFO "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
INFO "GET /admin/ HTTP/1.1" 200 6570
INFO "GET /admin/testapp/eagletails/ HTTP/1.1" 200 15189
INFO "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO "GET /admin/testapp/eagletails/1/change/ HTTP/1.1" 200 10200
INFO "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO "GET /admin/testapp/eagletails/ HTTP/1.1" 200 15189
INFO "POST /admin/testapp/eagletails/ HTTP/1.1" 200 8306
INFO "POST /admin/testapp/eagletails/ HTTP/1.1" 302 0
INFO "GET /admin/testapp/eagletails/ HTTP/1.1" 200 14820
INFO "GET /admin/jsi18n/ HTTP/1.1" 200 16066
